spring:
  profiles:
    active: dev
  application:
    name: owner-Information
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 47.93.202.227:8848

dubbo:
  registry:
    address: nacos://47.93.202.227:8848
  protocol:
    name: dubbo
    port: -1
  cloud:
    subscribed-services: owner-member




server:
  port: 8081